### PR TITLE
WIP: Convert deployment to helm chart

### PR DESCRIPTION
**Pull request by glb**
* Certificate creation done in Helm template -- certs and keys are stored in secrets
* Modified `certs.go` to read from mounted secrets
* Deployment converted to Helm

### CODE REVIEW

**Comment by glb** [comment]
I believe this will work as everything seems to deploy and start up, but I am pretty new to Kubernetes and don't know how to set up my apiserver with the required flags yet. (I know [what to do](https://kubernetes.io/docs/admin/extensible-admission-controllers/#enable-external-admission-webhooks), just not how to do it. Yet.)

_Yes, I know that the annotation is for Azure and I'm using `minikube`; I'm hoping that the admission control mechanism works so I can learn from and work with it regardless of whether my service will actually instantiate and do the right thing._

**Comment by glb** [comment]
I've tracked down the problem I'm having to my `apiserver` not knowing about `GenericAdmissionWebhook`:

```text
I0311 21:48:16.758118       1 server.go:121] Version: v1.9.0
I0311 21:48:17.530923       1 feature_gate.go:184] feature gates: map[Initializers:true]
I0311 21:48:17.530977       1 initialization.go:90] enabled Initializers feature as part of admission plugin setup
failed to initialize admission: Unknown admission plugin: GenericAdmissionWebhook
```

I'm using `gcr.io/google_containers/kube-apiserver-amd64:v1.9.0` which currently means `gcr.io/google_containers/kube-apiserver-amd64@sha256:47377f5df3ea25cb677fe081be78dce9ffe4a58dcaaa4191a0a9e8295cfb848b`.

I've tried `--feature-gates=AllAlpha=true` as a wild shot in the dark, but it didn't get me anywhere.

What have I missed?

**Comment by glb** [comment]
🕵 AHA: https://github.com/kubernetes/kubernetes/pull/55988 renamed `GenericAdmissionWebhook` to `ValidatingAdmissionWebhook` in 1.9, but the docs weren't updated!

```sh
minikube delete
minikube start \
  --bootstrapper kubeadm \
  --insecure-registry 10.0.1.4:5000   --extra-config=apiserver.admission-control="Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ValidatingAdmissionWebhook,ResourceQuota,PodPreset" \
  --extra-config=apiserver.runtime-config=admissionregistration.k8s.io/v1alpha1
```
at least allows `minikube` to initialize, and `apiserver` appears to be running with the right arguments:

```sh
kube-apiserver --admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ValidatingAdmissionWebhook,ResourceQuota,PodPreset --runtime-config=admissionregistration.k8s.io/v1alpha1 ...
```
but still not getting calls to the webhook because: 

```sh
{"log":"W0312 00:01:15.464640       1 admission.go:257] Failed calling webhook, failing open internallb-webhook-admission-controller.k8s.io: failed calling admission webhook \"internallb-webhook-admission-controller.k8s.io\": Post https://internallb-webhook-admission-controller.default.svc:443/services: dial tcp: lookup internallb-webhook-admission-controller.default.svc on 10.0.2.3:53: no such host\n","stream":"stderr","time":"2018-03-12T00:01:15.465320835Z"}
```

I've tried a couple of things so far:
1. installing the chart in the `kube-system` namespace (actually I needed to do that anyway because it wasn't running with permissions to access the configmap in `kube-system`
2. changing the `webhookConfig` to reference the service in `kube-system` instead of `default`.
3. renaming the webhook

... but I keep getting the failure to call the first one. In the absence of knowing how to delete this object (which feels like pretty basic knowledge I should be able to guess), I think my next step is to tear down the cluster and start it up again clean, then see if things come together.

**Comment by glb** [comment]
No dice -- I have no idea where this `internallb-webhook-admission-controller.default.svc` is coming from. Maybe something will occur to me overnight. :/

**Comment by glb** [comment]
@lachie83 have you seen the issue that I'm running into? Any thoughts on why the api server might be trying to resolve `internallb-webhook-admission-controller.default.svc`? I've completely torn down and replaced my "cluster" and there are literally no references to the `default` namespace anywhere in either the code or the steps I've been using.

Clearly you're not running into this issue as you seem to have a chart of your own that (presumably) works in #11 . I'll see if I can get things working with that.

**Comment by lachie83** [comment]
@glb First of all. Thanks for the contribution. I didn't expect anyone to be interested so quickly. I have done almost the same thing in #11 and I believe I have ironed out most kinks for now. Let me know if you would like to go with PR 11 or should I review this one?

**Comment by lachie83** [comment]
As for the API server it would depend on if you're running it in a container and what /etc/resolv.conf is doing to add suffixes

**Comment by glb** [comment]
Thanks! I'm running apiserver in a `minikube` environment bootstrapped by `kubeadm` ... so apiserver is running in a container. `resolv.conf` points to what I can only assume is `kubedns`, but I haven't dug deep enough to prove that yet.

**Comment by glb** [comment]
I'll take a look at #11 and see if anything jumps out at me that I might be doing wrong.

Related: I was thinking of enhancing this a bit so that you could specify namespace and possibly other bits when doing the install, but first I wanted to see it work. :)

**Comment by lachie83** [comment]
You should be able to install in any namespace using the helm chart `helm install chart-name directory --namespace kube-system`. LMK if that's not the case.

**Comment by lachie83** [comment]
I'm also testing on minikube

**Comment by glb** [comment]
re: namespaces: yes, looks great, this is definitely a much better way than what I was going to do (pass the namespace in to the registration code that you had previously written). 

re: minikube: I've done a `minikube delete`, used the `minikube start` command line that you have in your updated README, done the install, and my test service doesn't get blocked. BUT, with your branch I get a **much** better error:

```
{"log":"E0312 22:06:12.587260       1 admission.go:258] failed calling admission webhook \"geared-gecko-internallb-webhook-admission-controller.k8s.io\": Post https://geared-gecko-internallb-webhook-admission-controller.default.svc:443/mutating-services: dial tcp 10.96.225.178:443: getsockopt: connection refused\n","stream":"stderr","time":"2018-03-12T22:06:12.588072348Z"}
```

which I discover is a result of:

```
F0312 22:05:20.624174       1 config.go:118] mutatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:default:internallb-webhook-admission-controller" cannot create mutatingwebhookconfigurations.admissionregistration.k8s.io at the cluster scope
```

and since `config.go:118` doesn't exist anymore, I clearly am using the wrong image, which a `docker pull` shows me is true, but since changing `--set controller.ImagePullPolicy=Always` doesn't fix it, rebuilding the image and setting helm command line to pull from my local registry, aaaaand... rebuilding my `minikube` to trust my local registry, aaaand... fix my typo in the `helm install` so that it's a validating webhook (hint: that means I've tried it and the default mutating webhook WORKED), aaand BOOM:

```
Error from server (the service annotations do not contain required key and value): error when creating "examples/blocked-service.yml": admission webhook "unrealistic-beetle-internallb-webhook-admission-controller.k8s.io" denied the request: the service annotations do not contain required key and value
```

THANK YOU. I wish I knew why my version with your old code was getting the weird errors, but tbqh it is likely far more work and time than I want to put in to track down the issue at this point in time. Maybe it was the 1.9.0 vs 1.9.3. Maybe it was ghosts. I have something that works now. Thank you.

**Comment by lachie83** [comment]
Sorry. Please use the dev tag. Helm command is as follows:
```
helm install --name admission-webhook charts/internallb-webhook-admission-controller --set controller.imageTag=dev
```

**Comment by glb** [comment]
That works too, thanks :)

**Pull request closed without merging**
